### ISSUE TITLE
Ascenseurs de parcours de la fenêtre toujours présents

### ISSUE THREAD

**Issue by mobyFrag** [SocialGouv/archifiltre#1144]
Quelle que soit la taille de la fenêtre d'Archifiltre, pourtant je travaille sur un écran 27", les ascenseurs horizontal et vertical sont toujours présents.

Ca ne bloque pas l'usage de l'outil, juste une gêne visuelle ! D'autant que cela ne concerne que l'outil sans contenu : une fois un répertoire ouvert, les ascenseurs disparaissent.

![image](https://user-images.githubusercontent.com/61312262/102887609-876f6480-4457-11eb-8a2f-8d98e9635621.png)

**Comment by Alezco** [comment]
Bonjour @mobyFrag et merci pour cette remontée de bug. Il a été corrigé en décembre et sera donc dans la prochaine version, la 3.2.

**Comment by Alezco** [comment]
Bonjour @mobyFrag, la version 3.2 qui corrige ce bug est sortie ! Elle est téléchargeable ici : https://archifiltre.fabrique.social.gouv.fr/

Merci pour cette remontée de bug
