### ISSUE TITLE
Erreur dans le chargement des empreintes de fichiers et dossiers

### ISSUE THREAD

**Issue by MargueriteMuh** [SocialGouv/archifiltre#1322]
Lors du scan d'un dossier dans archifiltre le chargement des empreintes de fichiers et dossiers n'aboutit pas, empêchant par la même l'export du rapport d'audit ou du CSV. Le chargement reste bloqué à 82%.
Qu'est-ce qui peut bloquer ce chargement?

**Comment by Alezco** [comment]
Bonjour @MargueriteMuh. Merci pour ce signalement. Nous sommes au courant du problème qui sera corrigé dans la prochaine version d'Archifiltre. Merci pour votre patience :)

**Comment by Alezco** [comment]
Bonjour @MargueriteMuh. Le bug a été corrigé dans la nouvelle version 3.2.2 disponible sur https://archifiltre.fabrique.social.gouv.fr/
Merci pour le signalement :)
