### ISSUE TITLE
Erreur dans le chargement des empreintes empêchant le chargement complet et l'accès aux redondances

### ISSUE THREAD

**Issue by elsalouys** [SocialGouv/archifiltre#1343]
**Describe the bug**
Nous avons lancé une analyse directement sur un serveur Windows et un dossier d’environ 400 Go. Le chargement des empreintes bloque à 88% et le menu Redondances n’est pas accessible. Même constat sur des dossiers moins lourds et sur des analyses lancées sur des serveurs de fichiers linux à partir de notre poste. La liste des erreurs de chargement ne nous aide pas : erreur inconnue. De plus, concernant l’installation d’Archifiltre sur les serveurs Linux, nous avons un problème d’accès à des librairies partagées.
Notre dossier est-il trop volumineux ? qu'est-ce qui peut empêcher le chargement des empreintes ? Merci pour votre aide !

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 64-bit, MacOS Big Sur, Ubuntu 20.04]
 - Version [e.g. Archifiltre 3.1.1]
 
**Additional context**

**Comment by Alezco** [comment]
Bonjour. Ce bug a été identifié et corrigé dans la nouvelle version 3.2.2 disponible sur https://archifiltre.fabrique.social.gouv.fr/
Merci pour le signalement :)
