### ISSUE TITLE
Chargement des empreintes bloqué rendant impossible la création d'un export CSV, Excel 

### ISSUE THREAD

**Issue by MichelLux** [SocialGouv/archifiltre#1362]
Il semble que ce problème bloquant soit lié autant au nombre de fichiers qu'a leur poids. 
1 - Comme ce bug est signalé depuis quelques semaines, avez vous une "parade" permettant de réaliser des export sans empreinte par ex.  ?
2 - Pouvez vous communiquer sur une date de résolution du bug ?

**Comment by Loracahur** [comment]
Bonjour,

Config
Win 10 pro, proc Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz 2.11 GHz , ram 8Go, dossier de 9Go 14000 fichiers, archifiltre 3.2.2 (stable).
L'export Excel démarre puis reste à zéro. J'ai observé dans le gestionnaire de performance win. une crête maximale de l'utilisation mémoire lors du démarrage de l'export puis la crète descend est reste stable mais archifiltre semble ne plus être actif. J'ai fait le teste avec la même config mais avec alchifiltre 3.1.1. L'export se déroule bien et je n'ai pas observé la crête de consumation maximale de mémoire. Question : La configuration matériel présentée ci-dessous est-elle suffisante (mémoire) ?

**Comment by PorfiP** [comment]
Bonjour, 

Je suis nouveau dans cette communauté. J’utilise Archifiltre actuellement, mais j’éprouve de la difficulté à exporter le fichier en CSV avec la v4.0.0 (next. 10). En lisant les commentaires, j’ai cru comprendre que le problème de bogue pouvait être résolu avec cette version. De plus, mes collègues ont le même problème. Impossible d'exporter le CSV.
 
Avez-vous une piste de solution pour m’aider à avancer? 
Merci de votre collaboration. 

Porfirio
Techniciens en gestion de l’information (Documentation)
