### ISSUE TITLE
Blocage d'Archifiltre  lors de l'analyse d'un disque réseau

### ISSUE THREAD

**Issue by grimpozarbre** [SocialGouv/archifiltre#1577]
### User Story

SocialGouv/archifiltre-docs#

### Description du bug

Bonjour,
Après avoir réalisé un fichier pour analyser une arborescence réseau avec la procédure décrite ici : [https://github.com/SocialGouv/archifiltre-docs/wiki/Export-vers-Archifiltre-gr%C3%A2ce-%C3%A0-un-script-en-lignes-de-commande](url) et l'insertion de ce fichier dans Archifiltre, le système retourne un message d'erreur (rouge) indiquant : 

`TypeError: Cannot read properties of undefined (reading 'children')`

Le système indique bien le nombre de fichier analysé, mais il tourne en boucle et plus rien ne se passe.

### Étapes pour reproduire

1. Créer un fichier pour analyser une arborescence réseau Windows avec la procédure décrite ici : https://github.com/SocialGouv/archifiltre-docs/wiki/Export-vers-Archifiltre-gr%C3%A2ce-%C3%A0-un-script-en-lignes-de-commande
2. Glisser-déposer le fichier créé au point 1 dans Archifiltre

### Comportement attendu

Affichage du résultat de l'analyse d'Archifiltre identique à celui réalisé sur une arborescence locale.

### Captures d'écran (si possible)

![image](https://github.com/SocialGouv/archifiltre-docs/assets/896644/1b0588ba-2f1e-4e29-bb3d-77a883d6646c)

### Liste des caractéristiques de votre machine

- OS : Windows 10, 11, Mac OS Sonoma 14.2
- Ram : 16 Gb
- Version de l'application : Windows : (Setup, Portable), Mac OS : Dmg

### Version de l'application

4.x

**Comment by sam-pires** [comment]
Bonjour @grimpozarbre 

Le problème vient à priori des droits. Pouvez-vous vérifier si vous avez bien les droits de lecture sur le document généré ?
