### ISSUE TITLE
Etude du format d'entrée dans Resip

### ISSUE THREAD

**Issue by HeleneDam-benext** [SocialGouv/archifiltre#33]
ETQ dev, JV savoir quel est le format d'entrée csv attendu dans Resip afin de générer d'autres US sur l'epic 4.

**Comment by akakeronos** [comment]
Lorsque l'on génère un export csv de métadonnées depuis Resip on a une colonne Path qui indique le chemin des fichiers relativement au dossier analysé
Lorsque l'in génère un export RESIP depuis Archifiltre on a une colonne File qui indique le chemin des fichiers relativement au dossier analysé
Si on essaye de modifier manuellement l'export d'archifiltre pour renommer la colonne de File vers Path et que l'on utilise la fonction importer un csv de métadonnées dans Resip on a une erreur 

resip: erreur durant l'import, les données n'ont pas été modifiées
-> Le header [Path|Content.DescriptionLevel|Content.Title] est mal formatté. Il doit contenir au début soit une colonne File, soit deux colonnes File et ParentFile, soit trois colonnes ID, File et ParentFile ou ID, File et ParentID.

Cela signifie au passage que Resip ne peut pas importer de fichier csv de métadonnées à partir de fichiers générés dans Resip via la fonction export csv de métadonnées :)

Le résultat est que le fichier généré par Archifiltre est mal interprété par Resip et l'ensemble des lignes du tableau csv est considéré comme un archiveUnit au lieu de la distinction attendue entre archiveUnit et DataObject

Dans tous les cas même si le format d'export d'archifiltre était bien conforme à celui attendu par Resip ne faudrait-il pas qu'il indique les chemins absolus des fichiers et sous-dossiers plutôt qu'un chemion relatif au dossier analysé ?

**Comment by akakeronos** [comment]
Après échange avec l'équipe de Resip il suffit d'exporter le fichier Resip généré par Archifiltre dans le dossier analysé et l'import fonctionne
