### ISSUE TITLE
nom de colonne itératif pour le champ tag dans l'export RESIP

### ISSUE THREAD

**Issue by akakeronos** [SocialGouv/archifiltre#460]
Lorsque l'on effectue un export RESIP depuis archifiltre une colonne est créée pour chaque tag avec un intitulé incrémental (tag1, tag2, tag3, etc...)
Lors de l'import dans RESIP ce champ est transformé en balise xml en reprennant le même intitulé

En SEDA seule la balise Tag est valide https://www.francearchives.fr/seda/api_v2-1/seda-2_1-ontology_xsd.html#KeywordsGroup_Tag

Au passage ça serait super si on pouvait distinguer Tag et Keyword et brancher les vocabulaires du SIAF pour l'indexation contrôlée (au moins typologie documentaire et matière)

http://data.culture.fr/thesaurus/page/ark:/67717/T3-129
http://data.culture.fr/thesaurus/page/ark:/67717/Matiere

**Comment by cberthou** [comment]
Bonjour @akakeronos,

Nous allons regarder comment gérer cela dans les prochaines semaine.

**Comment by cberthou** [comment]
Pour l'ajout des vocabulaires du SIAF, nous sommes déjà en train de préparer ça, ça arrivera dans les prochaines semaines. Par contre, pour la distinction entre tag et keywords, nous allons étudier la question.

**Comment by akakeronos** [comment]
Bonjour @Alezco Non le problème est corrigé, merci !
En revanche il n'y a rien au bout du lien :)
J'ai récupéré la dernière version sur le dépôt GIthub

**Comment by Alezco** [comment]
Avec le lien j'ai bien accès au site d'archifiltre. Ensuite il suffit juste de sélectionner sa version (par défaut la dernière) et de cliquer sur le bouton "Découvrir l'application". Je ferme cette issue :)
