### ISSUE TITLE
Unités internationales de l'octet

### ISSUE THREAD

**Issue by tledoux** [SocialGouv/archifiltre#793]
Il est important de respecter les conversions du Système International.

Depuis plus de vingt ans maintenant, les unités ko, Mo et Go sont des multiples de puissance de 10.
https://fr.wikipedia.org/wiki/Octet#Multiples_normalis.C3.A9s

Si Microsoft continue de se tromper, c'est bien comme cela que sont calculées et vendues les capacités des disques durs.

Il convient donc de corriger les calculs ici :
https://github.com/SocialGouv/archifiltre/blob/4b822141b5f8e997ff3b440508a00837cafa2b02/src/components/modals/search-modal/filters/size-filter.tsx#L11
ou d'utiliser les préfixes binaires (Kio, Mio, Gio)

Merci

**Comment by Alezco** [comment]
Le problème a été corrigé dans la PR #794 qui a été mergée. Merci pour le retour !

**Comment by tledoux** [comment]
C'est parfait encore une fois.
Merci beaucoup ;-)
