### ISSUE TITLE
[FEATURE] Analyse longue : rafraîchir régulièrement la vue et prioriser les informations rapides

### ISSUE THREAD

**Issue by zptip** [SocialGouv/archifiltre#909]
L'analyse d'un dossier important se traduit par un écran figé et "Chargement des empreintes de fichiers et dossiers 1%".
Avec un risque de perdre des utilisateurs impatients ou qui supposeront que le programme ne marche pas.

Propositions : 
- rafraîchir souvent la vue et la laisser se construire plutôt que d'attendre la fin de l'analyse
- matérialiser les étapes (par exemple hachurer les dossiers avec empruntes à calculer, mettre un contour de cadre épais sur le dossier en cours d'analyse,..)
- prioriser les informations rapides à restituer et à utiliser (ex: préférable d'avoir rapidement la taille de seulement 3 niveaux plutôt que d'attendre une empreinte d'un niveau 20)
- au besoin un encart avec le nombre de fichiers/dossiers traités et à faire, le temps écoulé, et un bouton pour suspendre temporairement le rafraîchissement de la vue (le nb de fichier par contre continue de se mettre à jour)

**Comment by Alezco** [comment]
Bonjour @zptip, merci pour ces propositions.

La section en bas à droite qui affiche "Chargement des empreintes de fichiers et dossiers X%" se fait en tâche de fond ce qui permet d'utiliser le reste d'archifiltre, à l'exception des fonctionnalités utilisant les hashs, comme l'export CSV avec empreintes ou le rapport d'audit.
- L'analyse initiale de tous les dossiers et fichiers est nécessaire pour construire la vue des "stalactites", puisque la taille et la position de chacun dépend des autres.
- Changer l'apparence des éléments dont les hashs ne sont pas calculés est une bonne idée que nous notons et à laquelle nous allons réfléchir pour les prochaines versions.
- La manière dont nous calculons les empreintes fait que nous ne pouvons pas obtenir le hash du niveau N avant d'avoir calculé celles du niveau N + 1. Par conséquent, le dernier élément à avoir son empreinte calculée est le dossier racine du projet. Cependant, toutes les autres informations à l'exception du hash (taille, type de fichier, dates extrêmes etc) sont disponibles sur tous les éléments dès la fin du chargement initial.
- Nous allons aussi étudier pour la prochaine version l'idée d'un affichage du temps écoulé.

En plus de ces points, nous vous invitons à tester la V3 d'archifiltre, sortie aujourd'hui et disponible sur https://archifiltre.fabrique.social.gouv.fr/. En plus d'ajouter de nombreuses nouvelles fonctionnalités, elle propose une nette amélioration du temps initial d'analyse, et corrige plusieurs bugs sur le calcul des hashs/empreintes.

**Comment by Alezco** [comment]
Bonjour @zptip ! Je ferme l'issue, merci d'avoir fait ces propositions !
